### ISSUE TITLE
Established hotkey pattern?

### ISSUE THREAD

**Issue by meunierd** [RasmusEdgar/dintwm#1]
I just compiled off master last night and this works wonderfully! I was wondering if you've managed to bind it with FKey or anything else? I tried throwing it on my path and defining an FKey of `f5` with `Run Program` and `dintwm -g -s` but it just softlocks workbench 🤷‍♂

**Comment by RasmusEdgar** [comment]
Hi Meunierd,
Thanks for trying out dintwm!
I've implemented a way to customize hotkeys using the commodity library, I've updated the readme with instructions on how to do this. Please test that out.

I think your problem with FKey might be that you are calling both grid and spiral tile methods in the same command, which doesn't work. Why it locks up workbench, I need to look into. :)

**Comment by RasmusEdgar** [comment]
With the updated code on master I can't get it to crash with ```dintwm -g -s``` bound to F6, it simply does nothing. Also tested in FKey with:
F5 bound to "Run program" "<dintwm path>:dintwm -t"
F6 bound to "Run program" "<dintwm path>:dintwm -g"
F7 bound to "Run program" "<dintwm path>:dintwm -s"
F8 bound to "Run program" "<dintwm path>:dintwm -d"

And they all seem to work.

Also tested with custom topgap "-B120" which works

I see I need to do some work on -b option. The workbench bar gap is not accurate atm.

**Comment by meunierd** [comment]
The commodity settings work perfectly for me! The only thing I had to change was unchecking "Wait to Finished" for the provided dintwm.info. Cheers
