### ISSUE TITLE
Illegible message after booting

### ISSUE THREAD

**Issue by ghost** [RasmusEdgar/dintwm#2]
This message is displayed after booting
![dintwm](https://user-images.githubusercontent.com/1757768/114401649-091c0700-9b9b-11eb-9e80-cd540ca0f6d0.png)

The window is not resizable so the message is illegible. I'd suggest changing that somehow but also creating a tooltype to suppress this particular message.

dintwm is a fantastic application 👍

**Comment by RasmusEdgar** [comment]
Thanks for the nice words tenleftfingers. :smile: 

I have done some fixing and added the TT you requested.

INFO_OFF now suppresses the info windows.
The info windows are now adjusted in size to fit the text.

You can find a prelease with the features here:
https://github.com/RasmusEdgar/dintwm/releases/tag/v0.2-rc2

The README has been updated to reflect the changes as well.

Let me know if it fixes your issue.

**Comment by ghost** [comment]
Hi Rasmus,

This works exactly as intended, thank you so much!!
Issue resolved!

**Comment by RasmusEdgar** [comment]
Glad to hear it!
